[package]
name = "interpolate_derive"
version = "0.1.0"
edition = "2021"

[lib]
proc-macro = true

[dependencies]
nalgebra = { workspace = true }
syn = "2.0.60"
quote = "1.0.36"
proc-macro2 = "1.0.81"
